version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: devdb
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"

  test-backend:
    build: .
    environment:
      DATABASE_URL: postgres://your_user:your_password@devdb:5432/your_database
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

  db-migration:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://your_user:your_password@devdb:5432/your_database
    command: bash -c './wait-for-it.sh -h devdb -p 5432 && npx prisma migrate dev'
