

services:
  db:
    image: postgres:latest
    container_name: devdb
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"

  test-backend:
    build: .
    environment:
      DATABASE_URL: postgres://your_user:your_password@db:5432/your_database
      PORT: 8080
      MAIL_HOST: ${MAIL_HOST}
      EMAIL: ${EMAIL}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECTURI: ${REDIRECTURI}
      REFRESHTOKEN: ${REFRESHTOKEN}
      NASAAPI: ${NASAAPI}


    ports:
      - "8080:8080"
    depends_on:
      - db
    command: bash -c './wait-for-it.sh -h db -p 5432 --timeout=30 --strict -- npm start'

  db-migration:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://your_user:your_password@db:5432/your_database
    command: bash -c './wait-for-it.sh -h db -p 5432 --timeout=30 --strict -- npx prisma migrate dev'
